[0;33m--- esp-idf-monitor 1.6.2 on /dev/ttyACM0 115200[0m
[0;33m--- Quit: Ctrl+] | Menu: Ctrl+T | Help: Ctrl+T followed by Ctrl+H[0m
[0;33m--- 0x4004c51e: uart_rx_one_char in ROM
[0m
[0;33m--- Stack dump detected[0m
[0;33m--- 0x40387148: xTaskRemoveFromEventList at /home/happ/software/esp/esp-idf/components/freertos/FreeRTOS-Kernel/tasks.c:3995
--- 0x403857d4: xQueueGenericSendFromISR at /home/happ/software/esp/esp-idf/components/freertos/FreeRTOS-Kernel/queue.c:1264 (discriminator 1)
[0m
[0;33m--- 0x40380001: _vector_table at /home/happ/software/esp/esp-idf/components/riscv/vectors_intc.S:54
[0m
[0;33m--- Warning: Failed to run gdb_panic_server.py script: Command '['riscv32-esp-elf-gdb', '--batch', '-n', '/home/happ/project/esp/esp32_as_flash_burner/build/esp32_as_flash_burner.elf', '-ex', 'target remote | "/home/happ/.espressif/python_env/idf5.4_py3.13_env/bin/python" -m esp_idf_panic_decoder --target esp32c3 "/tmp/tmp6n80_dz8"', '-ex', 'bt']' returned non-zero exit status 1.
--- Warning: b'Traceback (most recent call last):\n  File "<frozen runpy>", line 198, in _run_module_as_main\n  File "<frozen runpy>", line 88, in _run_code\n  File "/home/happ/.espressif/python_env/idf5.4_py3.13_env/lib/python3.13/site-packages/esp_idf_panic_decoder/__main__.py", line 4, in <module>\n    main()\n    ~~~~^^\n  File "/home/happ/.espressif/python_env/idf5.4_py3.13_env/lib/python3.13/site-packages/esp_idf_panic_decoder/gdb_panic_server.py", line 289, in main\n    panic_info = PANIC_OUTPUT_PARSERS[args.target](args.input_file.read())\n  File "/home/happ/.espressif/python_env/idf5.4_py3.13_env/lib/python3.13/site-packages/esp_idf_panic_decoder/gdb_panic_server.py", line 152, in parse_idf_riscv_panic_output\n    stack_base_addr, stack_data = get_stack_addr_and_data(res)\n                                  ~~~~~~~~~~~~~~~~~~~~~~~^^^^^\n  File "/home/happ/.espressif/python_env/idf5.4_py3.13_env/lib/python3.13/site-packages/esp_idf_panic_decoder/gdb_panic_server.py", line 120, in get_stack_addr_and_data\n    assert base_addr == prev_base_addr + bytes_in_line\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nAssertionError\nRemote communication error.  Target disconnected: \xe8\xbf\x9e\xe6\x8e\xa5\xe8\xa2\xab\xe5\xaf\xb9\xe6\x96\xb9\xe9\x87\x8d\xe7\xbd\xae.\nNo stack.\n'

[0m
[0;33m--- 0x40380834: esp_restart_noos at /home/happ/software/esp/esp-idf/components/esp_system/port/soc/esp32c3/system_internal.c:112
[0m
[0;33m--- Stack dump detected[0m
[0;33m--- 0x4038087c: panic_abort at /home/happ/software/esp/esp-idf/components/esp_system/panic.c:468
--- 0x40384f38: __ubsan_include at /home/happ/software/esp/esp-idf/components/esp_system/ubsan.c:311
[0m
[0;33m--- 0x40380001: _vector_table at /home/happ/software/esp/esp-idf/components/riscv/vectors_intc.S:54
[0m
[0;33m--- Warning: Failed to run gdb_panic_server.py script: Command '['riscv32-esp-elf-gdb', '--batch', '-n', '/home/happ/project/esp/esp32_as_flash_burner/build/esp32_as_flash_burner.elf', '-ex', 'target remote | "/home/happ/.espressif/python_env/idf5.4_py3.13_env/bin/python" -m esp_idf_panic_decoder --target esp32c3 "/tmp/tmpwyb0x9ph"', '-ex', 'bt']' returned non-zero exit status 1.
--- Warning: b'Traceback (most recent call last):\n  File "<frozen runpy>", line 198, in _run_module_as_main\n  File "<frozen runpy>", line 88, in _run_code\n  File "/home/happ/.espressif/python_env/idf5.4_py3.13_env/lib/python3.13/site-packages/esp_idf_panic_decoder/__main__.py", line 4, in <module>\n    main()\n    ~~~~^^\n  File "/home/happ/.espressif/python_env/idf5.4_py3.13_env/lib/python3.13/site-packages/esp_idf_panic_decoder/gdb_panic_server.py", line 289, in main\n    panic_info = PANIC_OUTPUT_PARSERS[args.target](args.input_file.read())\n  File "/home/happ/.espressif/python_env/idf5.4_py3.13_env/lib/python3.13/site-packages/esp_idf_panic_decoder/gdb_panic_server.py", line 138, in parse_idf_riscv_panic_output\n    raise ValueError("Couldn\'t parse panic handler output")\nValueError: Couldn\'t parse panic handler output\nRemote communication error.  Target disconnected: \xe8\xbf\x9e\xe6\x8e\xa5\xe8\xa2\xab\xe5\xaf\xb9\xe6\x96\xb9\xe9\x87\x8d\xe7\xbd\xae.\nNo stack.\n'

[0m
[0;33m--- 0x40380834: esp_restart_noos at /home/happ/software/esp/esp-idf/components/esp_system/port/soc/esp32c3/system_internal.c:112
[0m
[0;33m--- Stack dump detected[0m
[0;33m--- 0x4038087c: panic_abort at /home/happ/software/esp/esp-idf/components/esp_system/panic.c:468
--- 0x40384f38: __ubsan_include at /home/happ/software/esp/esp-idf/components/esp_system/ubsan.c:311
[0m
[0;33m--- 0x40380001: _vector_table at /home/happ/software/esp/esp-idf/components/riscv/vectors_intc.S:54
[0m
[0;33m
--- Backtrace:

[0m
[0;33m--- 0x40380834: esp_restart_noos at /home/happ/software/esp/esp-idf/components/esp_system/port/soc/esp32c3/system_internal.c:112
[0m
[0;33m--- Stack dump detected[0m
[0;33m--- 0x4038087c: panic_abort at /home/happ/software/esp/esp-idf/components/esp_system/panic.c:468
--- 0x40384f38: __ubsan_include at /home/happ/software/esp/esp-idf/components/esp_system/ubsan.c:311
[0m
[0;33m--- 0x40380001: _vector_table at /home/happ/software/esp/esp-idf/components/riscv/vectors_intc.S:54
[0m
[0;33m
--- Backtrace:

[0m
[0;33m--- 0x40380834: esp_restart_noos at /home/happ/software/esp/esp-idf/components/esp_system/port/soc/esp32c3/system_internal.c:112
[0m
[0;33m--- Stack dump detected[0m
[0;33m--- 0x4038087c: panic_abort at /home/happ/software/esp/esp-idf/components/esp_system/panic.c:468
--- 0x40384f38: __ubsan_include at /home/happ/software/esp/esp-idf/components/esp_system/ubsan.c:311
[0m
[0;33m--- 0x40380001: _vector_table at /home/happ/software/esp/esp-idf/components/riscv/vectors_intc.S:54
[0m
[0;33m--- Warning: Failed to run gdb_panic_server.py script: Command '['riscv32-esp-elf-gdb', '--batch', '-n', '/home/happ/project/esp/esp32_as_flash_burner/build/esp32_as_flash_burner.elf', '-ex', 'target remote | "/home/happ/.espressif/python_env/idf5.4_py3.13_env/bin/python" -m esp_idf_panic_decoder --target esp32c3 "/tmp/tmpgx3u5k92"', '-ex', 'bt']' returned non-zero exit status 1.
--- Warning: b'Traceback (most recent call last):\n  File "<frozen runpy>", line 198, in _run_module_as_main\n  File "<frozen runpy>", line 88, in _run_code\n  File "/home/happ/.espressif/python_env/idf5.4_py3.13_env/lib/python3.13/site-packages/esp_idf_panic_decoder/__main__.py", line 4, in <module>\n    main()\n    ~~~~^^\n  File "/home/happ/.espressif/python_env/idf5.4_py3.13_env/lib/python3.13/site-packages/esp_idf_panic_decoder/gdb_panic_server.py", line 289, in main\n    panic_info = PANIC_OUTPUT_PARSERS[args.target](args.input_file.read())\n  File "/home/happ/.espressif/python_env/idf5.4_py3.13_env/lib/python3.13/site-packages/esp_idf_panic_decoder/gdb_panic_server.py", line 152, in parse_idf_riscv_panic_output\n    stack_base_addr, stack_data = get_stack_addr_and_data(res)\n                                  ~~~~~~~~~~~~~~~~~~~~~~~^^^^^\n  File "/home/happ/.espressif/python_env/idf5.4_py3.13_env/lib/python3.13/site-packages/esp_idf_panic_decoder/gdb_panic_server.py", line 120, in get_stack_addr_and_data\n    assert base_addr == prev_base_addr + bytes_in_line\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nAssertionError\nRemote communication error.  Target disconnected: \xe8\xbf\x9e\xe6\x8e\xa5\xe8\xa2\xab\xe5\xaf\xb9\xe6\x96\xb9\xe9\x87\x8d\xe7\xbd\xae.\nNo stack.\n'

[0m
[0;33m--- 0x40380834: esp_restart_noos at /home/happ/software/esp/esp-idf/components/esp_system/port/soc/esp32c3/system_internal.c:112
[0m
[0;33m--- Stack dump detected[0m
[0;33m--- 0x4038087c: panic_abort at /home/happ/software/esp/esp-idf/components/esp_system/panic.c:468
--- 0x40384f38: __ubsan_include at /home/happ/software/esp/esp-idf/components/esp_system/ubsan.c:311
[0m
[0;33m--- 0x40380001: _vector_table at /home/happ/software/esp/esp-idf/components/riscv/vectors_intc.S:54
[0m
[0;33m
--- Backtrace:

[0m
[0;33m--- 0x403848e0: systimer_ticks_to_us at /home/happ/software/esp/esp-idf/components/esp_hw_support/port/esp32c3/systimer.c:16
--- 0x403848ec: systimer_us_to_ticks at /home/happ/software/esp/esp-idf/components/esp_hw_support/port/esp32c3/systimer.c:21
[0m
[0;33m--- 0x4038134c: rtc_isr at /home/happ/software/esp/esp-idf/components/esp_hw_support/rtc_module.c:67
--- 0x403827a8: esp_crosscore_isr at /home/happ/software/esp/esp-idf/components/esp_system/crosscore_int.c:42
[0m
[0;33m--- 0x40386476: SysTickIsrHandler at /home/happ/software/esp/esp-idf/components/freertos/port_systick.c:127
--- 0x4200bf3a: task_wdt_isr at /home/happ/software/esp/esp-idf/components/esp_system/task_wdt/task_wdt.c:474
--- 0x4038363c: spi_intr at /home/happ/software/esp/esp-idf/components/esp_driver_spi/src/gpspi/spi_master.c:895
[0m
[0;33m--- 0x403819b6: usb_serial_jtag_sof_tick_hook at /home/happ/software/esp/esp-idf/components/esp_driver_usb_serial_jtag/src/usb_serial_jtag_connection_monitor.c:38
--- 0x40382896: tick_hook at /home/happ/software/esp/esp-idf/components/esp_system/int_wdt.c:104
[0m
[0;33m--- 0x4200be00: idle_hook_cb at /home/happ/software/esp/esp-idf/components/esp_system/task_wdt/task_wdt.c:456
[0m
[0;33m--- 0x40380834: esp_restart_noos at /home/happ/software/esp/esp-idf/components/esp_system/port/soc/esp32c3/system_internal.c:112
[0m
[0;33m--- Stack dump detected[0m
[0;33m--- 0x4038087c: panic_abort at /home/happ/software/esp/esp-idf/components/esp_system/panic.c:468
--- 0x40384f38: __ubsan_include at /home/happ/software/esp/esp-idf/components/esp_system/ubsan.c:311
[0m
[0;33m--- 0x40380001: _vector_table at /home/happ/software/esp/esp-idf/components/riscv/vectors_intc.S:54
[0m
[0;33m--- Warning: Failed to run gdb_panic_server.py script: Command '['riscv32-esp-elf-gdb', '--batch', '-n', '/home/happ/project/esp/esp32_as_flash_burner/build/esp32_as_flash_burner.elf', '-ex', 'target remote | "/home/happ/.espressif/python_env/idf5.4_py3.13_env/bin/python" -m esp_idf_panic_decoder --target esp32c3 "/tmp/tmp6srl9g0v"', '-ex', 'bt']' returned non-zero exit status 1.
--- Warning: b'Traceback (most recent call last):\n  File "<frozen runpy>", line 198, in _run_module_as_main\n  File "<frozen runpy>", line 88, in _run_code\n  File "/home/happ/.espressif/python_env/idf5.4_py3.13_env/lib/python3.13/site-packages/esp_idf_panic_decoder/__main__.py", line 4, in <module>\n    main()\n    ~~~~^^\n  File "/home/happ/.espressif/python_env/idf5.4_py3.13_env/lib/python3.13/site-packages/esp_idf_panic_decoder/gdb_panic_server.py", line 289, in main\n    panic_info = PANIC_OUTPUT_PARSERS[args.target](args.input_file.read())\n  File "/home/happ/.espressif/python_env/idf5.4_py3.13_env/lib/python3.13/site-packages/esp_idf_panic_decoder/gdb_panic_server.py", line 138, in parse_idf_riscv_panic_output\n    raise ValueError("Couldn\'t parse panic handler output")\nValueError: Couldn\'t parse panic handler output\nRemote communication error.  Target disconnected: \xe8\xbf\x9e\xe6\x8e\xa5\xe8\xa2\xab\xe5\xaf\xb9\xe6\x96\xb9\xe9\x87\x8d\xe7\xbd\xae.\nNo stack.\n'

[0m
[0;33m--- 0x40380834: esp_restart_noos at /home/happ/software/esp/esp-idf/components/esp_system/port/soc/esp32c3/system_internal.c:112
[0m
[0;33m--- Stack dump detected[0m
[0;33m--- 0x4038087c: panic_abort at /home/happ/software/esp/esp-idf/components/esp_system/panic.c:468
--- 0x40384f38: __ubsan_include at /home/happ/software/esp/esp-idf/components/esp_system/ubsan.c:311
[0m
[0;33m--- 0x40380001: _vector_table at /home/happ/software/esp/esp-idf/components/riscv/vectors_intc.S:54
[0m
[0;33m
--- Backtrace:

[0m
[0;33m--- 0x403848e0: systimer_ticks_to_us at /home/happ/software/esp/esp-idf/components/esp_hw_support/port/esp32c3/systimer.c:16
--- 0x403848ec: systimer_us_to_ticks at /home/happ/software/esp/esp-idf/components/esp_hw_support/port/esp32c3/systimer.c:21
[0m
[0;33m--- 0x4038134c: rtc_isr at /home/happ/software/esp/esp-idf/components/esp_hw_support/rtc_module.c:67
--- 0x403827a8: esp_crosscore_isr at /home/happ/software/esp/esp-idf/components/esp_system/crosscore_int.c:42
[0m
[0;33m--- 0x40386476: SysTickIsrHandler at /home/happ/software/esp/esp-idf/components/freertos/port_systick.c:127
--- 0x4200bf3a: task_wdt_isr at /home/happ/software/esp/esp-idf/components/esp_system/task_wdt/task_wdt.c:474
--- 0x4038363c: spi_intr at /home/happ/software/esp/esp-idf/components/esp_driver_spi/src/gpspi/spi_master.c:895
[0m
[0;33m--- 0x403819b6: usb_serial_jtag_sof_tick_hook at /home/happ/software/esp/esp-idf/components/esp_driver_usb_serial_jtag/src/usb_serial_jtag_connection_monitor.c:38
--- 0x40382896: tick_hook at /home/happ/software/esp/esp-idf/components/esp_system/int_wdt.c:104
[0m
[0;33m--- 0x4200be00: idle_hook_cb at /home/happ/software/esp/esp-idf/components/esp_system/task_wdt/task_wdt.c:456
[0m
[0;33m--- 0x40380834: esp_restart_noos at /home/happ/software/esp/esp-idf/components/esp_system/port/soc/esp32c3/system_internal.c:112
[0m
[0;33m--- Stack dump detected[0m
[0;33m--- 0x4038087c: panic_abort at /home/happ/software/esp/esp-idf/components/esp_system/panic.c:468
--- 0x40384f38: __ubsan_include at /home/happ/software/esp/esp-idf/components/esp_system/ubsan.c:311
[0m
[0;33m--- 0x40380001: _vector_table at /home/happ/software/esp/esp-idf/components/riscv/vectors_intc.S:54
[0m
[0;33m
--- Backtrace:

[0m
[0;33m--- 0x40380834: esp_restart_noos at /home/happ/software/esp/esp-idf/components/esp_system/port/soc/esp32c3/system_internal.c:112
[0m
[0;33m--- Stack dump detected[0m
[0;33m--- 0x4038087c: panic_abort at /home/happ/software/esp/esp-idf/components/esp_system/panic.c:468
--- 0x40384f38: __ubsan_include at /home/happ/software/esp/esp-idf/components/esp_system/ubsan.c:311
[0m
[0;33m--- 0x40380001: _vector_table at /home/happ/software/esp/esp-idf/components/riscv/vectors_intc.S:54
[0m
[0;33m
--- Backtrace:

[0m
[0;33m--- 0x40380834: esp_restart_noos at /home/happ/software/esp/esp-idf/components/esp_system/port/soc/esp32c3/system_internal.c:112
[0m
[0;33m--- Stack dump detected[0m
[0;33m--- 0x4038087c: panic_abort at /home/happ/software/esp/esp-idf/components/esp_system/panic.c:468
--- 0x40384f38: __ubsan_include at /home/happ/software/esp/esp-idf/components/esp_system/ubsan.c:311
[0m
[0;33m--- 0x40380001: _vector_table at /home/happ/software/esp/esp-idf/components/riscv/vectors_intc.S:54
[0m
[0;33m--- Warning: Failed to run gdb_panic_server.py script: Command '['riscv32-esp-elf-gdb', '--batch', '-n', '/home/happ/project/esp/esp32_as_flash_burner/build/esp32_as_flash_burner.elf', '-ex', 'target remote | "/home/happ/.espressif/python_env/idf5.4_py3.13_env/bin/python" -m esp_idf_panic_decoder --target esp32c3 "/tmp/tmpwmunbaz4"', '-ex', 'bt']' returned non-zero exit status 1.
--- Warning: b'Traceback (most recent call last):\n  File "<frozen runpy>", line 198, in _run_module_as_main\n  File "<frozen runpy>", line 88, in _run_code\n  File "/home/happ/.espressif/python_env/idf5.4_py3.13_env/lib/python3.13/site-packages/esp_idf_panic_decoder/__main__.py", line 4, in <module>\n    main()\n    ~~~~^^\n  File "/home/happ/.espressif/python_env/idf5.4_py3.13_env/lib/python3.13/site-packages/esp_idf_panic_decoder/gdb_panic_server.py", line 289, in main\n    panic_info = PANIC_OUTPUT_PARSERS[args.target](args.input_file.read())\n  File "/home/happ/.espressif/python_env/idf5.4_py3.13_env/lib/python3.13/site-packages/esp_idf_panic_decoder/gdb_panic_server.py", line 138, in parse_idf_riscv_panic_output\n    raise ValueError("Couldn\'t parse panic handler output")\nValueError: Couldn\'t parse panic handler output\nRemote communication error.  Target disconnected: \xe8\xbf\x9e\xe6\x8e\xa5\xe8\xa2\xab\xe5\xaf\xb9\xe6\x96\xb9\xe9\x87\x8d\xe7\xbd\xae.\nNo stack.\n'

[0m
[0;33m--- 0x403848e0: systimer_ticks_to_us at /home/happ/software/esp/esp-idf/components/esp_hw_support/port/esp32c3/systimer.c:16
--- 0x403848ec: systimer_us_to_ticks at /home/happ/software/esp/esp-idf/components/esp_hw_support/port/esp32c3/systimer.c:21
[0m
[0;33m--- 0x4038134c: rtc_isr at /home/happ/software/esp/esp-idf/components/esp_hw_support/rtc_module.c:67
--- 0x403827a8: esp_crosscore_isr at /home/happ/software/esp/esp-idf/components/esp_system/crosscore_int.c:42
[0m
[0;33m--- 0x40386476: SysTickIsrHandler at /home/happ/software/esp/esp-idf/components/freertos/port_systick.c:127
--- 0x4200bf3a: task_wdt_isr at /home/happ/software/esp/esp-idf/components/esp_system/task_wdt/task_wdt.c:474
--- 0x4038363c: spi_intr at /home/happ/software/esp/esp-idf/components/esp_driver_spi/src/gpspi/spi_master.c:895
[0m
[0;33m--- 0x403819b6: usb_serial_jtag_sof_tick_hook at /home/happ/software/esp/esp-idf/components/esp_driver_usb_serial_jtag/src/usb_serial_jtag_connection_monitor.c:38
--- 0x40382896: tick_hook at /home/happ/software/esp/esp-idf/components/esp_system/int_wdt.c:104
[0m
[0;33m--- 0x4200be00: idle_hook_cb at /home/happ/software/esp/esp-idf/components/esp_system/task_wdt/task_wdt.c:456
[0m
[0;33m--- 0x40380834: esp_restart_noos at /home/happ/software/esp/esp-idf/components/esp_system/port/soc/esp32c3/system_internal.c:112
[0m
[0;33m--- Stack dump detected[0m
[0;33m--- 0x4038087c: panic_abort at /home/happ/software/esp/esp-idf/components/esp_system/panic.c:468
--- 0x40384f38: __ubsan_include at /home/happ/software/esp/esp-idf/components/esp_system/ubsan.c:311
[0m
[0;33m--- 0x40380001: _vector_table at /home/happ/software/esp/esp-idf/components/riscv/vectors_intc.S:54
[0m
[0;33m
--- Backtrace:

[0m
[0;33m--- 0x40380834: esp_restart_noos at /home/happ/software/esp/esp-idf/components/esp_system/port/soc/esp32c3/system_internal.c:112
[0m
[0;33m--- Stack dump detected[0m
[0;33m--- 0x4038087c: panic_abort at /home/happ/software/esp/esp-idf/components/esp_system/panic.c:468
--- 0x40384f38: __ubsan_include at /home/happ/software/esp/esp-idf/components/esp_system/ubsan.c:311
[0m
[0;33m--- 0x40380001: _vector_table at /home/happ/software/esp/esp-idf/components/riscv/vectors_intc.S:54
[0m
[0;33m
--- Backtrace:

[0m
[0;33m--- 0x40380834: esp_restart_noos at /home/happ/software/esp/esp-idf/components/esp_system/port/soc/esp32c3/system_internal.c:112
[0m
[0;33m--- Stack dump detected[0m
[0;33m--- 0x4038087c: panic_abort at /home/happ/software/esp/esp-idf/components/esp_system/panic.c:468
--- 0x40384f38: __ubsan_include at /home/happ/software/esp/esp-idf/components/esp_system/ubsan.c:311
[0m
[0;33m--- 0x40380001: _vector_table at /home/happ/software/esp/esp-idf/components/riscv/vectors_intc.S:54
[0m
[0;33m--- Warning: Failed to run gdb_panic_server.py script: Command '['riscv32-esp-elf-gdb', '--batch', '-n', '/home/happ/project/esp/esp32_as_flash_burner/build/esp32_as_flash_burner.elf', '-ex', 'target remote | "/home/happ/.espressif/python_env/idf5.4_py3.13_env/bin/python" -m esp_idf_panic_decoder --target esp32c3 "/tmp/tmpswu84cri"', '-ex', 'bt']' returned non-zero exit status 1.
--- Warning: b'Traceback (most recent call last):\n  File "<frozen runpy>", line 198, in _run_module_as_main\n  File "<frozen runpy>", line 88, in _run_code\n  File "/home/happ/.espressif/python_env/idf5.4_py3.13_env/lib/python3.13/site-packages/esp_idf_panic_decoder/__main__.py", line 4, in <module>\n    main()\n    ~~~~^^\n  File "/home/happ/.espressif/python_env/idf5.4_py3.13_env/lib/python3.13/site-packages/esp_idf_panic_decoder/gdb_panic_server.py", line 289, in main\n    panic_info = PANIC_OUTPUT_PARSERS[args.target](args.input_file.read())\n  File "/home/happ/.espressif/python_env/idf5.4_py3.13_env/lib/python3.13/site-packages/esp_idf_panic_decoder/gdb_panic_server.py", line 138, in parse_idf_riscv_panic_output\n    raise ValueError("Couldn\'t parse panic handler output")\nValueError: Couldn\'t parse panic handler output\nRemote communication error.  Target disconnected: \xe8\xbf\x9e\xe6\x8e\xa5\xe8\xa2\xab\xe5\xaf\xb9\xe6\x96\xb9\xe9\x87\x8d\xe7\xbd\xae.\nNo stack.\n'

[0m
[0;33m--- 0x40380834: esp_restart_noos at /home/happ/software/esp/esp-idf/components/esp_system/port/soc/esp32c3/system_internal.c:112
[0m
[0;33m--- Stack dump detected[0m
[0;33m--- 0x4038087c: panic_abort at /home/happ/software/esp/esp-idf/components/esp_system/panic.c:468
--- 0x40384f38: __ubsan_include at /home/happ/software/esp/esp-idf/components/esp_system/ubsan.c:311
[0m
[0;33m--- 0x40380001: _vector_table at /home/happ/software/esp/esp-idf/components/riscv/vectors_intc.S:54
[0m
[0;33m
--- Backtrace:

[0m
[0;33m--- 0x40380834: esp_restart_noos at /home/happ/software/esp/esp-idf/components/esp_system/port/soc/esp32c3/system_internal.c:112
[0m
[0;33m--- Stack dump detected[0m
[0;33m--- 0x4038087c: panic_abort at /home/happ/software/esp/esp-idf/components/esp_system/panic.c:468
--- 0x40384f38: __ubsan_include at /home/happ/software/esp/esp-idf/components/esp_system/ubsan.c:311
[0m
[0;33m--- 0x40380001: _vector_table at /home/happ/software/esp/esp-idf/components/riscv/vectors_intc.S:54
[0m
[0;33m
--- Backtrace:

[0m
[0;33m--- 0x40380834: esp_restart_noos at /home/happ/software/esp/esp-idf/components/esp_system/port/soc/esp32c3/system_internal.c:112
[0m
[0;33m--- Stack dump detected[0m
[0;33m--- 0x4038087c: panic_abort at /home/happ/software/esp/esp-idf/components/esp_system/panic.c:468
[0m
[0;33m--- 0x40384f38: __ubsan_include at /home/happ/software/esp/esp-idf/components/esp_system/ubsan.c:311
[0m
[0;33m--- 0x40380001: _vector_table at /home/happ/software/esp/esp-idf/components/riscv/vectors_intc.S:54
[0m
[0;33m--- Warning: Failed to run gdb_panic_server.py script: Command '['riscv32-esp-elf-gdb', '--batch', '-n', '/home/happ/project/esp/esp32_as_flash_burner/build/esp32_as_flash_burner.elf', '-ex', 'target remote | "/home/happ/.espressif/python_env/idf5.4_py3.13_env/bin/python" -m esp_idf_panic_decoder --target esp32c3 "/tmp/tmp6erkbv4i"', '-ex', 'bt']' returned non-zero exit status 1.
--- Warning: b'Traceback (most recent call last):\n  File "<frozen runpy>", line 198, in _run_module_as_main\n  File "<frozen runpy>", line 88, in _run_code\n  File "/home/happ/.espressif/python_env/idf5.4_py3.13_env/lib/python3.13/site-packages/esp_idf_panic_decoder/__main__.py", line 4, in <module>\n    main()\n    ~~~~^^\n  File "/home/happ/.espressif/python_env/idf5.4_py3.13_env/lib/python3.13/site-packages/esp_idf_panic_decoder/gdb_panic_server.py", line 289, in main\n    panic_info = PANIC_OUTPUT_PARSERS[args.target](args.input_file.read())\n  File "/home/happ/.espressif/python_env/idf5.4_py3.13_env/lib/python3.13/site-packages/esp_idf_panic_decoder/gdb_panic_server.py", line 138, in parse_idf_riscv_panic_output\n    raise ValueError("Couldn\'t parse panic handler output")\nValueError: Couldn\'t parse panic handler output\nRemote communication error.  Target disconnected: \xe8\xbf\x9e\xe6\x8e\xa5\xe8\xa2\xab\xe5\xaf\xb9\xe6\x96\xb9\xe9\x87\x8d\xe7\xbd\xae.\nNo stack.\n'

[0m
[0;33m--- 0x40380834: esp_restart_noos at /home/happ/software/esp/esp-idf/components/esp_system/port/soc/esp32c3/system_internal.c:112
[0m
[0;33m--- Stack dump detected[0m
[0;33m--- 0x4038087c: panic_abort at /home/happ/software/esp/esp-idf/components/esp_system/panic.c:468
--- 0x40384f38: __ubsan_include at /home/happ/software/esp/esp-idf/components/esp_system/ubsan.c:311
[0m
[0;33m--- 0x40380001: _vector_table at /home/happ/software/esp/esp-idf/components/riscv/vectors_intc.S:54
[0m
[0;33m--- Warning: Failed to run gdb_panic_server.py script: Command '['riscv32-esp-elf-gdb', '--batch', '-n', '/home/happ/project/esp/esp32_as_flash_burner/build/esp32_as_flash_burner.elf', '-ex', 'target remote | "/home/happ/.espressif/python_env/idf5.4_py3.13_env/bin/python" -m esp_idf_panic_decoder --target esp32c3 "/tmp/tmp4cvvmxai"', '-ex', 'bt']' returned non-zero exit status 1.
--- Warning: b'Traceback (most recent call last):\n  File "<frozen runpy>", line 198, in _run_module_as_main\n  File "<frozen runpy>", line 88, in _run_code\n  File "/home/happ/.espressif/python_env/idf5.4_py3.13_env/lib/python3.13/site-packages/esp_idf_panic_decoder/__main__.py", line 4, in <module>\n    main()\n    ~~~~^^\n  File "/home/happ/.espressif/python_env/idf5.4_py3.13_env/lib/python3.13/site-packages/esp_idf_panic_decoder/gdb_panic_server.py", line 289, in main\n    panic_info = PANIC_OUTPUT_PARSERS[args.target](args.input_file.read())\n  File "/home/happ/.espressif/python_env/idf5.4_py3.13_env/lib/python3.13/site-packages/esp_idf_panic_decoder/gdb_panic_server.py", line 138, in parse_idf_riscv_panic_output\n    raise ValueError("Couldn\'t parse panic handler output")\nValueError: Couldn\'t parse panic handler output\nRemote communication error.  Target disconnected: \xe8\xbf\x9e\xe6\x8e\xa5\xe8\xa2\xab\xe5\xaf\xb9\xe6\x96\xb9\xe9\x87\x8d\xe7\xbd\xae.\nNo stack.\n'

[0m
[0;33m--- 0x403848e0: systimer_ticks_to_us at /home/happ/software/esp/esp-idf/components/esp_hw_support/port/esp32c3/systimer.c:16
--- 0x403848ec: systimer_us_to_ticks at /home/happ/software/esp/esp-idf/components/esp_hw_support/port/esp32c3/systimer.c:21
[0m
[0;33m--- 0x4038134c: rtc_isr at /home/happ/software/esp/esp-idf/components/esp_hw_support/rtc_module.c:67
--- 0x403827a8: esp_crosscore_isr at /home/happ/software/esp/esp-idf/components/esp_system/crosscore_int.c:42
[0m
[0;33m--- 0x40386476: SysTickIsrHandler at /home/happ/software/esp/esp-idf/components/freertos/port_systick.c:127
--- 0x4200bf3a: task_wdt_isr at /home/happ/software/esp/esp-idf/components/esp_system/task_wdt/task_wdt.c:474
--- 0x4038363c: spi_intr at /home/happ/software/esp/esp-idf/components/esp_driver_spi/src/gpspi/spi_master.c:895
[0m
[0;33m--- 0x403819b6: usb_serial_jtag_sof_tick_hook at /home/happ/software/esp/esp-idf/components/esp_driver_usb_serial_jtag/src/usb_serial_jtag_connection_monitor.c:38
--- 0x40382896: tick_hook at /home/happ/software/esp/esp-idf/components/esp_system/int_wdt.c:104
[0m
[0;33m--- 0x4200be00: idle_hook_cb at /home/happ/software/esp/esp-idf/components/esp_system/task_wdt/task_wdt.c:456
[0m
[0;33m--- 0x40380834: esp_restart_noos at /home/happ/software/esp/esp-idf/components/esp_system/port/soc/esp32c3/system_internal.c:112
[0m
[0;33m--- Stack dump detected[0m
[0;33m--- 0x4038087c: panic_abort at /home/happ/software/esp/esp-idf/components/esp_system/panic.c:468
--- 0x40384f38: __ubsan_include at /home/happ/software/esp/esp-idf/components/esp_system/ubsan.c:311
[0m
[0;33m--- 0x40380001: _vector_table at /home/happ/software/esp/esp-idf/components/riscv/vectors_intc.S:54
[0m
[0;33m
--- Backtrace:

[0m
[0;33m--- 0x40380834: esp_restart_noos at /home/happ/software/esp/esp-idf/components/esp_system/port/soc/esp32c3/system_internal.c:112
[0m
[0;33m--- Stack dump detected[0m
[0;33m--- 0x4038087c: panic_abort at /home/happ/software/esp/esp-idf/components/esp_system/panic.c:468
--- 0x40384f38: __ubsan_include at /home/happ/software/esp/esp-idf/components/esp_system/ubsan.c:311
[0m
[0;33m--- 0x40380001: _vector_table at /home/happ/software/esp/esp-idf/components/riscv/vectors_intc.S:54
[0m
[0;33m
--- Backtrace:

[0m
[0;33m--- 0x40380834: esp_restart_noos at /home/happ/software/esp/esp-idf/components/esp_system/port/soc/esp32c3/system_internal.c:112
[0m
[0;33m--- Stack dump detected[0m
[0;33m--- 0x4038087c: panic_abort at /home/happ/software/esp/esp-idf/components/esp_system/panic.c:468
--- 0x40384f38: __ubsan_include at /home/happ/software/esp/esp-idf/components/esp_system/ubsan.c:311
[0m
[0;33m--- 0x40380001: _vector_table at /home/happ/software/esp/esp-idf/components/riscv/vectors_intc.S:54
[0m
[0;33m--- Warning: Failed to run gdb_panic_server.py script: Command '['riscv32-esp-elf-gdb', '--batch', '-n', '/home/happ/project/esp/esp32_as_flash_burner/build/esp32_as_flash_burner.elf', '-ex', 'target remote | "/home/happ/.espressif/python_env/idf5.4_py3.13_env/bin/python" -m esp_idf_panic_decoder --target esp32c3 "/tmp/tmpp8_62gm6"', '-ex', 'bt']' returned non-zero exit status 1.
--- Warning: b'Traceback (most recent call last):\n  File "<frozen runpy>", line 198, in _run_module_as_main\n  File "<frozen runpy>", line 88, in _run_code\n  File "/home/happ/.espressif/python_env/idf5.4_py3.13_env/lib/python3.13/site-packages/esp_idf_panic_decoder/__main__.py", line 4, in <module>\n    main()\n    ~~~~^^\n  File "/home/happ/.espressif/python_env/idf5.4_py3.13_env/lib/python3.13/site-packages/esp_idf_panic_decoder/gdb_panic_server.py", line 289, in main\n    panic_info = PANIC_OUTPUT_PARSERS[args.target](args.input_file.read())\n  File "/home/happ/.espressif/python_env/idf5.4_py3.13_env/lib/python3.13/site-packages/esp_idf_panic_decoder/gdb_panic_server.py", line 138, in parse_idf_riscv_panic_output\n    raise ValueError("Couldn\'t parse panic handler output")\nValueError: Couldn\'t parse panic handler output\nRemote communication error.  Target disconnected: \xe8\xbf\x9e\xe6\x8e\xa5\xe8\xa2\xab\xe5\xaf\xb9\xe6\x96\xb9\xe9\x87\x8d\xe7\xbd\xae.\nNo stack.\n'

[0m
[0;33m--- 0x40380834: esp_restart_noos at /home/happ/software/esp/esp-idf/components/esp_system/port/soc/esp32c3/system_internal.c:112
[0m
[0;33m--- Stack dump detected[0m
[0;33m--- 0x4038087c: panic_abort at /home/happ/software/esp/esp-idf/components/esp_system/panic.c:468
--- 0x40384f38: __ubsan_include at /home/happ/software/esp/esp-idf/components/esp_system/ubsan.c:311
[0m
[0;33m--- 0x40380001: _vector_table at /home/happ/software/esp/esp-idf/components/riscv/vectors_intc.S:54
[0m
[0;33m
--- Backtrace:

[0m
[0;33m--- 0x40380834: esp_restart_noos at /home/happ/software/esp/esp-idf/components/esp_system/port/soc/esp32c3/system_internal.c:112
[0m
[0;33m--- Stack dump detected[0m
[0;33m--- 0x4038087c: panic_abort at /home/happ/software/esp/esp-idf/components/esp_system/panic.c:468
--- 0x40384f38: __ubsan_include at /home/happ/software/esp/esp-idf/components/esp_system/ubsan.c:311
[0m
[0;33m--- 0x40380001: _vector_table at /home/happ/software/esp/esp-idf/components/riscv/vectors_intc.S:54
[0m
[0;33m--- Warning: Failed to run gdb_panic_server.py script: Command '['riscv32-esp-elf-gdb', '--batch', '-n', '/home/happ/project/esp/esp32_as_flash_burner/build/esp32_as_flash_burner.elf', '-ex', 'target remote | "/home/happ/.espressif/python_env/idf5.4_py3.13_env/bin/python" -m esp_idf_panic_decoder --target esp32c3 "/tmp/tmpn6k3cjyn"', '-ex', 'bt']' returned non-zero exit status 1.
--- Warning: b'Traceback (most recent call last):\n  File "<frozen runpy>", line 198, in _run_module_as_main\n  File "<frozen runpy>", line 88, in _run_code\n  File "/home/happ/.espressif/python_env/idf5.4_py3.13_env/lib/python3.13/site-packages/esp_idf_panic_decoder/__main__.py", line 4, in <module>\n    main()\n    ~~~~^^\n  File "/home/happ/.espressif/python_env/idf5.4_py3.13_env/lib/python3.13/site-packages/esp_idf_panic_decoder/gdb_panic_server.py", line 289, in main\n    panic_info = PANIC_OUTPUT_PARSERS[args.target](args.input_file.read())\n  File "/home/happ/.espressif/python_env/idf5.4_py3.13_env/lib/python3.13/site-packages/esp_idf_panic_decoder/gdb_panic_server.py", line 138, in parse_idf_riscv_panic_output\n    raise ValueError("Couldn\'t parse panic handler output")\nValueError: Couldn\'t parse panic handler output\nRemote communication error.  Target disconnected: \xe8\xbf\x9e\xe6\x8e\xa5\xe8\xa2\xab\xe5\xaf\xb9\xe6\x96\xb9\xe9\x87\x8d\xe7\xbd\xae.\nNo stack.\n'

[0m
[0;33m--- 0x40380834: esp_restart_noos at /home/happ/software/esp/esp-idf/components/esp_system/port/soc/esp32c3/system_internal.c:112
[0m
[0;33m--- Stack dump detected[0m
[0;33m--- 0x4038087c: panic_abort at /home/happ/software/esp/esp-idf/components/esp_system/panic.c:468
--- 0x40384f38: __ubsan_include at /home/happ/software/esp/esp-idf/components/esp_system/ubsan.c:311
[0m
[0;33m--- 0x40380001: _vector_table at /home/happ/software/esp/esp-idf/components/riscv/vectors_intc.S:54
[0m
[0;33m
--- Backtrace:

[0m
[0;33m--- 0x40380834: esp_restart_noos at /home/happ/software/esp/esp-idf/components/esp_system/port/soc/esp32c3/system_internal.c:112
[0m
[0;33m--- Stack dump detected[0m
[0;33m--- 0x4038087c: panic_abort at /home/happ/software/esp/esp-idf/components/esp_system/panic.c:468
[0m
[0;33m--- 0x40384f38: __ubsan_include at /home/happ/software/esp/esp-idf/components/esp_system/ubsan.c:311
[0m
[0;33m--- 0x40380001: _vector_table at /home/happ/software/esp/esp-idf/components/riscv/vectors_intc.S:54
[0m
[0;33m--- Warning: Failed to run gdb_panic_server.py script: Command '['riscv32-esp-elf-gdb', '--batch', '-n', '/home/happ/project/esp/esp32_as_flash_burner/build/esp32_as_flash_burner.elf', '-ex', 'target remote | "/home/happ/.espressif/python_env/idf5.4_py3.13_env/bin/python" -m esp_idf_panic_decoder --target esp32c3 "/tmp/tmpsdczjk_g"', '-ex', 'bt']' returned non-zero exit status 1.
--- Warning: b'Traceback (most recent call last):\n  File "<frozen runpy>", line 198, in _run_module_as_main\n  File "<frozen runpy>", line 88, in _run_code\n  File "/home/happ/.espressif/python_env/idf5.4_py3.13_env/lib/python3.13/site-packages/esp_idf_panic_decoder/__main__.py", line 4, in <module>\n    main()\n    ~~~~^^\n  File "/home/happ/.espressif/python_env/idf5.4_py3.13_env/lib/python3.13/site-packages/esp_idf_panic_decoder/gdb_panic_server.py", line 289, in main\n    panic_info = PANIC_OUTPUT_PARSERS[args.target](args.input_file.read())\n  File "/home/happ/.espressif/python_env/idf5.4_py3.13_env/lib/python3.13/site-packages/esp_idf_panic_decoder/gdb_panic_server.py", line 138, in parse_idf_riscv_panic_output\n    raise ValueError("Couldn\'t parse panic handler output")\nValueError: Couldn\'t parse panic handler output\nRemote communication error.  Target disconnected: \xe8\xbf\x9e\xe6\x8e\xa5\xe8\xa2\xab\xe5\xaf\xb9\xe6\x96\xb9\xe9\x87\x8d\xe7\xbd\xae.\nNo stack.\n'

[0m
[0;33m--- 0x40380834: esp_restart_noos at /home/happ/software/esp/esp-idf/components/esp_system/port/soc/esp32c3/system_internal.c:112
[0m
[0;33m--- Stack dump detected[0m
[0;33m--- 0x4038087c: panic_abort at /home/happ/software/esp/esp-idf/components/esp_system/panic.c:468
--- 0x40384f38: __ubsan_include at /home/happ/software/esp/esp-idf/components/esp_system/ubsan.c:311
[0m
[0;33m--- 0x40380001: _vector_table at /home/happ/software/esp/esp-idf/components/riscv/vectors_intc.S:54
[0m
[0;33m--- Warning: Failed to run gdb_panic_server.py script: Command '['riscv32-esp-elf-gdb', '--batch', '-n', '/home/happ/project/esp/esp32_as_flash_burner/build/esp32_as_flash_burner.elf', '-ex', 'target remote | "/home/happ/.espressif/python_env/idf5.4_py3.13_env/bin/python" -m esp_idf_panic_decoder --target esp32c3 "/tmp/tmp3vdy7024"', '-ex', 'bt']' returned non-zero exit status 1.
--- Warning: b'Traceback (most recent call last):\n  File "<frozen runpy>", line 198, in _run_module_as_main\n  File "<frozen runpy>", line 88, in _run_code\n  File "/home/happ/.espressif/python_env/idf5.4_py3.13_env/lib/python3.13/site-packages/esp_idf_panic_decoder/__main__.py", line 4, in <module>\n    main()\n    ~~~~^^\n  File "/home/happ/.espressif/python_env/idf5.4_py3.13_env/lib/python3.13/site-packages/esp_idf_panic_decoder/gdb_panic_server.py", line 289, in main\n    panic_info = PANIC_OUTPUT_PARSERS[args.target](args.input_file.read())\n  File "/home/happ/.espressif/python_env/idf5.4_py3.13_env/lib/python3.13/site-packages/esp_idf_panic_decoder/gdb_panic_server.py", line 152, in parse_idf_riscv_panic_output\n    stack_base_addr, stack_data = get_stack_addr_and_data(res)\n                                  ~~~~~~~~~~~~~~~~~~~~~~~^^^^^\n  File "/home/happ/.espressif/python_env/idf5.4_py3.13_env/lib/python3.13/site-packages/esp_idf_panic_decoder/gdb_panic_server.py", line 120, in get_stack_addr_and_data\n    assert base_addr == prev_base_addr + bytes_in_line\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nAssertionError\nRemote communication error.  Target disconnected: \xe8\xbf\x9e\xe6\x8e\xa5\xe8\xa2\xab\xe5\xaf\xb9\xe6\x96\xb9\xe9\x87\x8d\xe7\xbd\xae.\nNo stack.\n'

[0m
[0;33m--- 0x40380834: esp_restart_noos at /home/happ/software/esp/esp-idf/components/esp_system/port/soc/esp32c3/system_internal.c:112
[0m
[0;33m--- Stack dump detected[0m
[0;33m--- 0x4038087c: panic_abort at /home/happ/software/esp/esp-idf/components/esp_system/panic.c:468
--- 0x40384f38: __ubsan_include at /home/happ/software/esp/esp-idf/components/esp_system/ubsan.c:311
[0m
[0;33m--- 0x40380001: _vector_table at /home/happ/software/esp/esp-idf/components/riscv/vectors_intc.S:54
[0m
[0;33m
--- Backtrace:

[0m
[0;33m--- 0x40380834: esp_restart_noos at /home/happ/software/esp/esp-idf/components/esp_system/port/soc/esp32c3/system_internal.c:112
[0m
[0;33m--- Stack dump detected[0m
[0;33m--- 0x4038087c: panic_abort at /home/happ/software/esp/esp-idf/components/esp_system/panic.c:468
[0m
[0;33m--- 0x40384f38: __ubsan_include at /home/happ/software/esp/esp-idf/components/esp_system/ubsan.c:311
[0m
[0;33m--- 0x40380001: _vector_table at /home/happ/software/esp/esp-idf/components/riscv/vectors_intc.S:54
[0m
[0;33m--- Warning: Failed to run gdb_panic_server.py script: Command '['riscv32-esp-elf-gdb', '--batch', '-n', '/home/happ/project/esp/esp32_as_flash_burner/build/esp32_as_flash_burner.elf', '-ex', 'target remote | "/home/happ/.espressif/python_env/idf5.4_py3.13_env/bin/python" -m esp_idf_panic_decoder --target esp32c3 "/tmp/tmp9h393ok_"', '-ex', 'bt']' returned non-zero exit status 1.
--- Warning: b'Traceback (most recent call last):\n  File "<frozen runpy>", line 198, in _run_module_as_main\n  File "<frozen runpy>", line 88, in _run_code\n  File "/home/happ/.espressif/python_env/idf5.4_py3.13_env/lib/python3.13/site-packages/esp_idf_panic_decoder/__main__.py", line 4, in <module>\n    main()\n    ~~~~^^\n  File "/home/happ/.espressif/python_env/idf5.4_py3.13_env/lib/python3.13/site-packages/esp_idf_panic_decoder/gdb_panic_server.py", line 289, in main\n    panic_info = PANIC_OUTPUT_PARSERS[args.target](args.input_file.read())\n  File "/home/happ/.espressif/python_env/idf5.4_py3.13_env/lib/python3.13/site-packages/esp_idf_panic_decoder/gdb_panic_server.py", line 138, in parse_idf_riscv_panic_output\n    raise ValueError("Couldn\'t parse panic handler output")\nValueError: Couldn\'t parse panic handler output\nRemote communication error.  Target disconnected: \xe8\xbf\x9e\xe6\x8e\xa5\xe8\xa2\xab\xe5\xaf\xb9\xe6\x96\xb9\xe9\x87\x8d\xe7\xbd\xae.\nNo stack.\n'

[0m
[0;33m--- 0x40380834: esp_restart_noos at /home/happ/software/esp/esp-idf/components/esp_system/port/soc/esp32c3/system_internal.c:112
[0m
[0;33m--- Stack dump detected[0m
[0;33m--- 0x4038087c: panic_abort at /home/happ/software/esp/esp-idf/components/esp_system/panic.c:468
--- 0x40384f38: __ubsan_include at /home/happ/software/esp/esp-idf/components/esp_system/ubsan.c:311
[0m
[0;33m--- 0x40380001: _vector_table at /home/happ/software/esp/esp-idf/components/riscv/vectors_intc.S:54
[0m
[0;33m
--- Backtrace:

[0m
[0;33m--- 0x40380834: esp_restart_noos at /home/happ/software/esp/esp-idf/components/esp_system/port/soc/esp32c3/system_internal.c:112
[0m
[0;33m--- Stack dump detected[0m
[0;33m--- 0x4038087c: panic_abort at /home/happ/software/esp/esp-idf/components/esp_system/panic.c:468
--- 0x40384f38: __ubsan_include at /home/happ/software/esp/esp-idf/components/esp_system/ubsan.c:311
[0m
[0;33m--- 0x40380001: _vector_table at /home/happ/software/esp/esp-idf/components/riscv/vectors_intc.S:54
[0m
[0;33m--- Warning: Failed to run gdb_panic_server.py script: Command '['riscv32-esp-elf-gdb', '--batch', '-n', '/home/happ/project/esp/esp32_as_flash_burner/build/esp32_as_flash_burner.elf', '-ex', 'target remote | "/home/happ/.espressif/python_env/idf5.4_py3.13_env/bin/python" -m esp_idf_panic_decoder --target esp32c3 "/tmp/tmp1pmfvt3l"', '-ex', 'bt']' returned non-zero exit status 1.
--- Warning: b'Traceback (most recent call last):\n  File "<frozen runpy>", line 198, in _run_module_as_main\n  File "<frozen runpy>", line 88, in _run_code\n  File "/home/happ/.espressif/python_env/idf5.4_py3.13_env/lib/python3.13/site-packages/esp_idf_panic_decoder/__main__.py", line 4, in <module>\n    main()\n    ~~~~^^\n  File "/home/happ/.espressif/python_env/idf5.4_py3.13_env/lib/python3.13/site-packages/esp_idf_panic_decoder/gdb_panic_server.py", line 289, in main\n    panic_info = PANIC_OUTPUT_PARSERS[args.target](args.input_file.read())\n  File "/home/happ/.espressif/python_env/idf5.4_py3.13_env/lib/python3.13/site-packages/esp_idf_panic_decoder/gdb_panic_server.py", line 138, in parse_idf_riscv_panic_output\n    raise ValueError("Couldn\'t parse panic handler output")\nValueError: Couldn\'t parse panic handler output\nRemote communication error.  Target disconnected: \xe8\xbf\x9e\xe6\x8e\xa5\xe8\xa2\xab\xe5\xaf\xb9\xe6\x96\xb9\xe9\x87\x8d\xe7\xbd\xae.\nNo stack.\n'

[0m
[0;33m--- 0x40380834: esp_restart_noos at /home/happ/software/esp/esp-idf/components/esp_system/port/soc/esp32c3/system_internal.c:112
[0m
[0;33m--- Stack dump detected[0m
[0;33m--- 0x4038087c: panic_abort at /home/happ/software/esp/esp-idf/components/esp_system/panic.c:468
--- 0x40384f38: __ubsan_include at /home/happ/software/esp/esp-idf/components/esp_system/ubsan.c:311
[0m
[0;33m--- 0x40380001: _vector_table at /home/happ/software/esp/esp-idf/components/riscv/vectors_intc.S:54
[0m
[0;33m--- Warning: Failed to run gdb_panic_server.py script: Command '['riscv32-esp-elf-gdb', '--batch', '-n', '/home/happ/project/esp/esp32_as_flash_burner/build/esp32_as_flash_burner.elf', '-ex', 'target remote | "/home/happ/.espressif/python_env/idf5.4_py3.13_env/bin/python" -m esp_idf_panic_decoder --target esp32c3 "/tmp/tmp3p1vpais"', '-ex', 'bt']' returned non-zero exit status 1.
--- Warning: b'Traceback (most recent call last):\n  File "<frozen runpy>", line 198, in _run_module_as_main\n  File "<frozen runpy>", line 88, in _run_code\n  File "/home/happ/.espressif/python_env/idf5.4_py3.13_env/lib/python3.13/site-packages/esp_idf_panic_decoder/__main__.py", line 4, in <module>\n    main()\n    ~~~~^^\n  File "/home/happ/.espressif/python_env/idf5.4_py3.13_env/lib/python3.13/site-packages/esp_idf_panic_decoder/gdb_panic_server.py", line 289, in main\n    panic_info = PANIC_OUTPUT_PARSERS[args.target](args.input_file.read())\n  File "/home/happ/.espressif/python_env/idf5.4_py3.13_env/lib/python3.13/site-packages/esp_idf_panic_decoder/gdb_panic_server.py", line 152, in parse_idf_riscv_panic_output\n    stack_base_addr, stack_data = get_stack_addr_and_data(res)\n                                  ~~~~~~~~~~~~~~~~~~~~~~~^^^^^\n  File "/home/happ/.espressif/python_env/idf5.4_py3.13_env/lib/python3.13/site-packages/esp_idf_panic_decoder/gdb_panic_server.py", line 120, in get_stack_addr_and_data\n    assert base_addr == prev_base_addr + bytes_in_line\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nAssertionError\nRemote communication error.  Target disconnected: \xe8\xbf\x9e\xe6\x8e\xa5\xe8\xa2\xab\xe5\xaf\xb9\xe6\x96\xb9\xe9\x87\x8d\xe7\xbd\xae.\nNo stack.\n'

[0m
[0;33m--- 0x40380834: esp_restart_noos at /home/happ/software/esp/esp-idf/components/esp_system/port/soc/esp32c3/system_internal.c:112
[0m
[0;33m--- Stack dump detected[0m
[0;33m--- 0x4038087c: panic_abort at /home/happ/software/esp/esp-idf/components/esp_system/panic.c:468
--- 0x40384f38: __ubsan_include at /home/happ/software/esp/esp-idf/components/esp_system/ubsan.c:311
[0m
[0;33m--- 0x40380001: _vector_table at /home/happ/software/esp/esp-idf/components/riscv/vectors_intc.S:54
[0m
[0;33m
--- Backtrace:

[0m
[0;33m--- 0x40380834: esp_restart_noos at /home/happ/software/esp/esp-idf/components/esp_system/port/soc/esp32c3/system_internal.c:112
[0m
[0;33m--- Stack dump detected[0m
[0;33m--- 0x4038087c: panic_abort at /home/happ/software/esp/esp-idf/components/esp_system/panic.c:468
--- 0x40384f38: __ubsan_include at /home/happ/software/esp/esp-idf/components/esp_system/ubsan.c:311
[0m
[0;33m--- 0x40380001: _vector_table at /home/happ/software/esp/esp-idf/components/riscv/vectors_intc.S:54
[0m
[0;33m
--- Backtrace:

[0m
[0;33m--- 0x40380834: esp_restart_noos at /home/happ/software/esp/esp-idf/components/esp_system/port/soc/esp32c3/system_internal.c:112
[0m
[0;33m--- Stack dump detected[0m
[0;33m--- 0x4038087c: panic_abort at /home/happ/software/esp/esp-idf/components/esp_system/panic.c:468
--- 0x40384f38: __ubsan_include at /home/happ/software/esp/esp-idf/components/esp_system/ubsan.c:311
[0m
[0;33m--- 0x40380001: _vector_table at /home/happ/software/esp/esp-idf/components/riscv/vectors_intc.S:54
[0m
[0;33m--- Warning: Failed to run gdb_panic_server.py script: Command '['riscv32-esp-elf-gdb', '--batch', '-n', '/home/happ/project/esp/esp32_as_flash_burner/build/esp32_as_flash_burner.elf', '-ex', 'target remote | "/home/happ/.espressif/python_env/idf5.4_py3.13_env/bin/python" -m esp_idf_panic_decoder --target esp32c3 "/tmp/tmp7heenq4h"', '-ex', 'bt']' returned non-zero exit status 1.
--- Warning: b'Traceback (most recent call last):\n  File "<frozen runpy>", line 198, in _run_module_as_main\n  File "<frozen runpy>", line 88, in _run_code\n  File "/home/happ/.espressif/python_env/idf5.4_py3.13_env/lib/python3.13/site-packages/esp_idf_panic_decoder/__main__.py", line 4, in <module>\n    main()\n    ~~~~^^\n  File "/home/happ/.espressif/python_env/idf5.4_py3.13_env/lib/python3.13/site-packages/esp_idf_panic_decoder/gdb_panic_server.py", line 289, in main\n    panic_info = PANIC_OUTPUT_PARSERS[args.target](args.input_file.read())\n  File "/home/happ/.espressif/python_env/idf5.4_py3.13_env/lib/python3.13/site-packages/esp_idf_panic_decoder/gdb_panic_server.py", line 152, in parse_idf_riscv_panic_output\n    stack_base_addr, stack_data = get_stack_addr_and_data(res)\n                                  ~~~~~~~~~~~~~~~~~~~~~~~^^^^^\n  File "/home/happ/.espressif/python_env/idf5.4_py3.13_env/lib/python3.13/site-packages/esp_idf_panic_decoder/gdb_panic_server.py", line 120, in get_stack_addr_and_data\n    assert base_addr == prev_base_addr + bytes_in_line\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nAssertionError\nRemote communication error.  Target disconnected: \xe8\xbf\x9e\xe6\x8e\xa5\xe8\xa2\xab\xe5\xaf\xb9\xe6\x96\xb9\xe9\x87\x8d\xe7\xbd\xae.\nNo stack.\n'

[0m
[0;33m--- 0x40380834: esp_restart_noos at /home/happ/software/esp/esp-idf/components/esp_system/port/soc/esp32c3/system_internal.c:112
[0m
[0;33m--- Stack dump detected[0m
[0;33m--- 0x4038087c: panic_abort at /home/happ/software/esp/esp-idf/components/esp_system/panic.c:468
--- 0x40384f38: __ubsan_include at /home/happ/software/esp/esp-idf/components/esp_system/ubsan.c:311
[0m
[0;33m--- 0x40380001: _vector_table at /home/happ/software/esp/esp-idf/components/riscv/vectors_intc.S:54
[0m
[0;33m--- Warning: Failed to run gdb_panic_server.py script: Command '['riscv32-esp-elf-gdb', '--batch', '-n', '/home/happ/project/esp/esp32_as_flash_burner/build/esp32_as_flash_burner.elf', '-ex', 'target remote | "/home/happ/.espressif/python_env/idf5.4_py3.13_env/bin/python" -m esp_idf_panic_decoder --target esp32c3 "/tmp/tmp8k9y0ow2"', '-ex', 'bt']' returned non-zero exit status 1.
--- Warning: b'Traceback (most recent call last):\n  File "<frozen runpy>", line 198, in _run_module_as_main\n  File "<frozen runpy>", line 88, in _run_code\n  File "/home/happ/.espressif/python_env/idf5.4_py3.13_env/lib/python3.13/site-packages/esp_idf_panic_decoder/__main__.py", line 4, in <module>\n    main()\n    ~~~~^^\n  File "/home/happ/.espressif/python_env/idf5.4_py3.13_env/lib/python3.13/site-packages/esp_idf_panic_decoder/gdb_panic_server.py", line 289, in main\n    panic_info = PANIC_OUTPUT_PARSERS[args.target](args.input_file.read())\n  File "/home/happ/.espressif/python_env/idf5.4_py3.13_env/lib/python3.13/site-packages/esp_idf_panic_decoder/gdb_panic_server.py", line 138, in parse_idf_riscv_panic_output\n    raise ValueError("Couldn\'t parse panic handler output")\nValueError: Couldn\'t parse panic handler output\nRemote communication error.  Target disconnected: \xe8\xbf\x9e\xe6\x8e\xa5\xe8\xa2\xab\xe5\xaf\xb9\xe6\x96\xb9\xe9\x87\x8d\xe7\xbd\xae.\nNo stack.\n'

[0m
[0;33m--- 0x40380834: esp_restart_noos at /home/happ/software/esp/esp-idf/components/esp_system/port/soc/esp32c3/system_internal.c:112
[0m
[0;33m--- Stack dump detected[0m
[0;33m--- 0x4038087c: panic_abort at /home/happ/software/esp/esp-idf/components/esp_system/panic.c:468
--- 0x40384f38: __ubsan_include at /home/happ/software/esp/esp-idf/components/esp_system/ubsan.c:311
[0m
[0;33m--- 0x40380001: _vector_table at /home/happ/software/esp/esp-idf/components/riscv/vectors_intc.S:54
[0m
[0;33m
--- Backtrace:

[0m
[0;33m--- 0x40380834: esp_restart_noos at /home/happ/software/esp/esp-idf/components/esp_system/port/soc/esp32c3/system_internal.c:112
[0m
[0m
