[0;33m--- esp-idf-monitor 1.6.2 on /dev/ttyACM0 115200[0m
[0;33m--- Quit: Ctrl+] | Menu: Ctrl+T | Help: Ctrl+T followed by Ctrl+H[0m
[0;33m--- 0x4004c97a: usb_uart_rx_one_char in ROM
[0m
[0;33m--- Stack dump detected[0m
[0;33m--- 0x42010ae8: _vfprintf_r at /builds/idf/crosstool-NG/.build/riscv32-esp-elf/src/newlib/newlib/libc/stdio/vfprintf.c:846
--- 0x42010ad6: _vfprintf_r at /builds/idf/crosstool-NG/.build/riscv32-esp-elf/src/newlib/newlib/libc/stdio/vfprintf.c:845
[0m
[0;33m--- 0x4005890e: memset in ROM
[0m
[0;33m--- 0x40380001: _vector_table at /home/happ/software/esp/esp-idf/components/riscv/vectors_intc.S:54
[0m
[0;33m
--- Backtrace:

[0m
[0;33m--- 0x40380834: esp_restart_noos at /home/happ/software/esp/esp-idf/components/esp_system/port/soc/esp32c3/system_internal.c:112
[0m
[0;33m--- Stack dump detected[0m
[0;33m--- 0x42010ae6: _vfprintf_r at /builds/idf/crosstool-NG/.build/riscv32-esp-elf/src/newlib/newlib/libc/stdio/vfprintf.c:846
[0m
[0;33m--- 0x4005890e: memset in ROM
--- 0x403817e0: __retarget_lock_acquire_recursive at /home/happ/software/esp/esp-idf/components/newlib/locks.c:322
[0m
[0;33m--- 0x40380001: _vector_table at /home/happ/software/esp/esp-idf/components/riscv/vectors_intc.S:54
[0m
[0;33m--- Warning: Failed to run gdb_panic_server.py script: Command '['riscv32-esp-elf-gdb', '--batch', '-n', '/home/happ/project/esp/esp32_as_flash_burner/build/esp32_as_flash_burner.elf', '-ex', 'target remote | "/home/happ/.espressif/python_env/idf5.4_py3.13_env/bin/python" -m esp_idf_panic_decoder --target esp32c3 "/tmp/tmp27x6_4w4"', '-ex', 'bt']' returned non-zero exit status 1.
--- Warning: b'Traceback (most recent call last):\n  File "<frozen runpy>", line 198, in _run_module_as_main\n  File "<frozen runpy>", line 88, in _run_code\n  File "/home/happ/.espressif/python_env/idf5.4_py3.13_env/lib/python3.13/site-packages/esp_idf_panic_decoder/__main__.py", line 4, in <module>\n    main()\n    ~~~~^^\n  File "/home/happ/.espressif/python_env/idf5.4_py3.13_env/lib/python3.13/site-packages/esp_idf_panic_decoder/gdb_panic_server.py", line 289, in main\n    panic_info = PANIC_OUTPUT_PARSERS[args.target](args.input_file.read())\n  File "/home/happ/.espressif/python_env/idf5.4_py3.13_env/lib/python3.13/site-packages/esp_idf_panic_decoder/gdb_panic_server.py", line 138, in parse_idf_riscv_panic_output\n    raise ValueError("Couldn\'t parse panic handler output")\nValueError: Couldn\'t parse panic handler output\nRemote communication error.  Target disconnected: \xe8\xbf\x9e\xe6\x8e\xa5\xe8\xa2\xab\xe5\xaf\xb9\xe6\x96\xb9\xe9\x87\x8d\xe7\xbd\xae.\nNo stack.\n'

[0m
[0;33m--- 0x40380834: esp_restart_noos at /home/happ/software/esp/esp-idf/components/esp_system/port/soc/esp32c3/system_internal.c:112
[0m
[0;33m--- Stack dump detected[0m
[0;33m--- 0x42010ae8: _vfprintf_r at /builds/idf/crosstool-NG/.build/riscv32-esp-elf/src/newlib/newlib/libc/stdio/vfprintf.c:846
--- 0x42010ae6: _vfprintf_r at /builds/idf/crosstool-NG/.build/riscv32-esp-elf/src/newlib/newlib/libc/stdio/vfprintf.c:846
[0m
[0;33m--- 0x4005890e: memset in ROM
--- 0x403817e0: __retarget_lock_acquire_recursive at /home/happ/software/esp/esp-idf/components/newlib/locks.c:322
[0m
[0;33m--- 0x40380001: _vector_table at /home/happ/software/esp/esp-idf/components/riscv/vectors_intc.S:54
[0m
[0;33m
--- Backtrace:

[0m
[0;33m--- 0x40380834: esp_restart_noos at /home/happ/software/esp/esp-idf/components/esp_system/port/soc/esp32c3/system_internal.c:112
[0m
[0;33m--- Stack dump detected[0m
[0;33m--- 0x42010ae8: _vfprintf_r at /builds/idf/crosstool-NG/.build/riscv32-esp-elf/src/newlib/newlib/libc/stdio/vfprintf.c:846
--- 0x42010ad6: _vfprintf_r at /builds/idf/crosstool-NG/.build/riscv32-esp-elf/src/newlib/newlib/libc/stdio/vfprintf.c:845
[0m
[0;33m--- 0x4005890e: memset in ROM
[0m
[0;33m--- 0x40380001: _vector_table at /home/happ/software/esp/esp-idf/components/riscv/vectors_intc.S:54
[0m
[0;33m
--- Backtrace:

[0m
[0;33m--- 0x40380834: esp_restart_noos at /home/happ/software/esp/esp-idf/components/esp_system/port/soc/esp32c3/system_internal.c:112
[0m
[0;33m--- Stack dump detected[0m
[0;33m--- 0x42010ae8: _vfprintf_r at /builds/idf/crosstool-NG/.build/riscv32-esp-elf/src/newlib/newlib/libc/stdio/vfprintf.c:846
--- 0x42010ad6: _vfprintf_r at /builds/idf/crosstool-NG/.build/riscv32-esp-elf/src/newlib/newlib/libc/stdio/vfprintf.c:845
[0m
[0;33m--- 0x4005890e: memset in ROM
[0m
[0;33m--- 0x40380001: _vector_table at /home/happ/software/esp/esp-idf/components/riscv/vectors_intc.S:54
[0m
[0;33m
--- Backtrace:

[0m
[0;33m--- 0x40380834: esp_restart_noos at /home/happ/software/esp/esp-idf/components/esp_system/port/soc/esp32c3/system_internal.c:112
[0m
[0;33m--- Stack dump detected[0m
[0;33m--- 0x42010ae8: _vfprintf_r at /builds/idf/crosstool-NG/.build/riscv32-esp-elf/src/newlib/newlib/libc/stdio/vfprintf.c:846
--- 0x42010ae6: _vfprintf_r at /builds/idf/crosstool-NG/.build/riscv32-esp-elf/src/newlib/newlib/libc/stdio/vfprintf.c:846
[0m
[0;33m--- 0x4005890e: memset in ROM
--- 0x403817e0: __retarget_lock_acquire_recursive at /home/happ/software/esp/esp-idf/components/newlib/locks.c:322
[0m
[0;33m--- 0x40380001: _vector_table at /home/happ/software/esp/esp-idf/components/riscv/vectors_intc.S:54
[0m
[0;33m
--- Backtrace:

[0m
[0;33m--- 0x40380834: esp_restart_noos at /home/happ/software/esp/esp-idf/components/esp_system/port/soc/esp32c3/system_internal.c:112
[0m
[0;33m--- Stack dump detected[0m
[0;33m--- 0x42010ae8: _vfprintf_r at /builds/idf/crosstool-NG/.build/riscv32-esp-elf/src/newlib/newlib/libc/stdio/vfprintf.c:846
--- 0x42010ae6: _vfprintf_r at /builds/idf/crosstool-NG/.build/riscv32-esp-elf/src/newlib/newlib/libc/stdio/vfprintf.c:846
[0m
[0;33m--- 0x4005890e: memset in ROM
--- 0x403817e0: __retarget_lock_acquire_recursive at /home/happ/software/esp/esp-idf/components/newlib/locks.c:322
[0m
[0;33m--- 0x40380001: _vector_table at /home/happ/software/esp/esp-idf/components/riscv/vectors_intc.S:54
[0m
[0;33m
--- Backtrace:

[0m
[0;33m--- 0x40380834: esp_restart_noos at /home/happ/software/esp/esp-idf/components/esp_system/port/soc/esp32c3/system_internal.c:112
[0m
[0;33m--- Stack dump detected[0m
[0;33m--- 0x42010ae8: _vfprintf_r at /builds/idf/crosstool-NG/.build/riscv32-esp-elf/src/newlib/newlib/libc/stdio/vfprintf.c:846
--- 0x42010ad6: _vfprintf_r at /builds/idf/crosstool-NG/.build/riscv32-esp-elf/src/newlib/newlib/libc/stdio/vfprintf.c:845
[0m
[0;33m--- 0x4005890e: memset in ROM
[0m
[0;33m--- 0x40380001: _vector_table at /home/happ/software/esp/esp-idf/components/riscv/vectors_intc.S:54
[0m
[0;33m--- Warning: Failed to run gdb_panic_server.py script: Command '['riscv32-esp-elf-gdb', '--batch', '-n', '/home/happ/project/esp/esp32_as_flash_burner/build/esp32_as_flash_burner.elf', '-ex', 'target remote | "/home/happ/.espressif/python_env/idf5.4_py3.13_env/bin/python" -m esp_idf_panic_decoder --target esp32c3 "/tmp/tmp80xer9hv"', '-ex', 'bt']' returned non-zero exit status 1.
--- Warning: b'Traceback (most recent call last):\n  File "<frozen runpy>", line 198, in _run_module_as_main\n  File "<frozen runpy>", line 88, in _run_code\n  File "/home/happ/.espressif/python_env/idf5.4_py3.13_env/lib/python3.13/site-packages/esp_idf_panic_decoder/__main__.py", line 4, in <module>\n    main()\n    ~~~~^^\n  File "/home/happ/.espressif/python_env/idf5.4_py3.13_env/lib/python3.13/site-packages/esp_idf_panic_decoder/gdb_panic_server.py", line 289, in main\n    panic_info = PANIC_OUTPUT_PARSERS[args.target](args.input_file.read())\n  File "/home/happ/.espressif/python_env/idf5.4_py3.13_env/lib/python3.13/site-packages/esp_idf_panic_decoder/gdb_panic_server.py", line 152, in parse_idf_riscv_panic_output\n    stack_base_addr, stack_data = get_stack_addr_and_data(res)\n                                  ~~~~~~~~~~~~~~~~~~~~~~~^^^^^\n  File "/home/happ/.espressif/python_env/idf5.4_py3.13_env/lib/python3.13/site-packages/esp_idf_panic_decoder/gdb_panic_server.py", line 120, in get_stack_addr_and_data\n    assert base_addr == prev_base_addr + bytes_in_line\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nAssertionError\nRemote communication error.  Target disconnected: \xe8\xbf\x9e\xe6\x8e\xa5\xe8\xa2\xab\xe5\xaf\xb9\xe6\x96\xb9\xe9\x87\x8d\xe7\xbd\xae.\nNo stack.\n'

[0m
[0;33m--- 0x40380834: esp_restart_noos at /home/happ/software/esp/esp-idf/components/esp_system/port/soc/esp32c3/system_internal.c:112
[0m
[0;33m--- Stack dump detected[0m
[0;33m--- 0x42010ae8: _vfprintf_r at /builds/idf/crosstool-NG/.build/riscv32-esp-elf/src/newlib/newlib/libc/stdio/vfprintf.c:846
--- 0x42010ad6: _vfprintf_r at /builds/idf/crosstool-NG/.build/riscv32-esp-elf/src/newlib/newlib/libc/stdio/vfprintf.c:845
[0m
[0;33m--- 0x4005890e: memset in ROM
[0m
[0;33m--- 0x40380001: _vector_table at /home/happ/software/esp/esp-idf/components/riscv/vectors_intc.S:54
[0m
[0;33m--- Warning: Failed to run gdb_panic_server.py script: Command '['riscv32-esp-elf-gdb', '--batch', '-n', '/home/happ/project/esp/esp32_as_flash_burner/build/esp32_as_flash_burner.elf', '-ex', 'target remote | "/home/happ/.espressif/python_env/idf5.4_py3.13_env/bin/python" -m esp_idf_panic_decoder --target esp32c3 "/tmp/tmpwk2ytqym"', '-ex', 'bt']' returned non-zero exit status 1.
--- Warning: b'Traceback (most recent call last):\n  File "<frozen runpy>", line 198, in _run_module_as_main\n  File "<frozen runpy>", line 88, in _run_code\n  File "/home/happ/.espressif/python_env/idf5.4_py3.13_env/lib/python3.13/site-packages/esp_idf_panic_decoder/__main__.py", line 4, in <module>\n    main()\n    ~~~~^^\n  File "/home/happ/.espressif/python_env/idf5.4_py3.13_env/lib/python3.13/site-packages/esp_idf_panic_decoder/gdb_panic_server.py", line 289, in main\n    panic_info = PANIC_OUTPUT_PARSERS[args.target](args.input_file.read())\n  File "/home/happ/.espressif/python_env/idf5.4_py3.13_env/lib/python3.13/site-packages/esp_idf_panic_decoder/gdb_panic_server.py", line 138, in parse_idf_riscv_panic_output\n    raise ValueError("Couldn\'t parse panic handler output")\nValueError: Couldn\'t parse panic handler output\nRemote communication error.  Target disconnected: \xe8\xbf\x9e\xe6\x8e\xa5\xe8\xa2\xab\xe5\xaf\xb9\xe6\x96\xb9\xe9\x87\x8d\xe7\xbd\xae.\nNo stack.\n'

[0m
[0;33m--- 0x40380834: esp_restart_noos at /home/happ/software/esp/esp-idf/components/esp_system/port/soc/esp32c3/system_internal.c:112
[0m
[0;33m--- Stack dump detected[0m
[0;33m--- 0x42010ae8: _vfprintf_r at /builds/idf/crosstool-NG/.build/riscv32-esp-elf/src/newlib/newlib/libc/stdio/vfprintf.c:846
--- 0x42010ae6: _vfprintf_r at /builds/idf/crosstool-NG/.build/riscv32-esp-elf/src/newlib/newlib/libc/stdio/vfprintf.c:846
[0m
[0;33m--- 0x4005890e: memset in ROM
--- 0x403817e0: __retarget_lock_acquire_recursive at /home/happ/software/esp/esp-idf/components/newlib/locks.c:322
[0m
[0;33m--- 0x40380001: _vector_table at /home/happ/software/esp/esp-idf/components/riscv/vectors_intc.S:54
[0m
[0;33m
--- Backtrace:

[0m
[0;33m--- 0x40380834: esp_restart_noos at /home/happ/software/esp/esp-idf/components/esp_system/port/soc/esp32c3/system_internal.c:112
[0m
[0;33m--- Stack dump detected[0m
[0;33m--- 0x42010ae8: _vfprintf_r at /builds/idf/crosstool-NG/.build/riscv32-esp-elf/src/newlib/newlib/libc/stdio/vfprintf.c:846
--- 0x42010ae6: _vfprintf_r at /builds/idf/crosstool-NG/.build/riscv32-esp-elf/src/newlib/newlib/libc/stdio/vfprintf.c:846
[0m
[0;33m--- 0x4005890e: memset in ROM
--- 0x403817e0: __retarget_lock_acquire_recursive at /home/happ/software/esp/esp-idf/components/newlib/locks.c:322
[0m
[0;33m--- 0x40380001: _vector_table at /home/happ/software/esp/esp-idf/components/riscv/vectors_intc.S:54
[0m
[0;33m--- Warning: Failed to run gdb_panic_server.py script: Command '['riscv32-esp-elf-gdb', '--batch', '-n', '/home/happ/project/esp/esp32_as_flash_burner/build/esp32_as_flash_burner.elf', '-ex', 'target remote | "/home/happ/.espressif/python_env/idf5.4_py3.13_env/bin/python" -m esp_idf_panic_decoder --target esp32c3 "/tmp/tmpsg9v_tbp"', '-ex', 'bt']' returned non-zero exit status 1.
--- Warning: b'Traceback (most recent call last):\n  File "<frozen runpy>", line 198, in _run_module_as_main\n  File "<frozen runpy>", line 88, in _run_code\n  File "/home/happ/.espressif/python_env/idf5.4_py3.13_env/lib/python3.13/site-packages/esp_idf_panic_decoder/__main__.py", line 4, in <module>\n    main()\n    ~~~~^^\n  File "/home/happ/.espressif/python_env/idf5.4_py3.13_env/lib/python3.13/site-packages/esp_idf_panic_decoder/gdb_panic_server.py", line 289, in main\n    panic_info = PANIC_OUTPUT_PARSERS[args.target](args.input_file.read())\n  File "/home/happ/.espressif/python_env/idf5.4_py3.13_env/lib/python3.13/site-packages/esp_idf_panic_decoder/gdb_panic_server.py", line 138, in parse_idf_riscv_panic_output\n    raise ValueError("Couldn\'t parse panic handler output")\nValueError: Couldn\'t parse panic handler output\nRemote communication error.  Target disconnected: \xe8\xbf\x9e\xe6\x8e\xa5\xe8\xa2\xab\xe5\xaf\xb9\xe6\x96\xb9\xe9\x87\x8d\xe7\xbd\xae.\nNo stack.\n'

[0m
[0;33m--- 0x40380834: esp_restart_noos at /home/happ/software/esp/esp-idf/components/esp_system/port/soc/esp32c3/system_internal.c:112
[0m
[0;33m--- Stack dump detected[0m
[0;33m--- 0x42010ae8: _vfprintf_r at /builds/idf/crosstool-NG/.build/riscv32-esp-elf/src/newlib/newlib/libc/stdio/vfprintf.c:846
--- 0x42010ad6: _vfprintf_r at /builds/idf/crosstool-NG/.build/riscv32-esp-elf/src/newlib/newlib/libc/stdio/vfprintf.c:845
[0m
[0;33m--- 0x4005890e: memset in ROM
[0m
[0;33m--- 0x40380001: _vector_table at /home/happ/software/esp/esp-idf/components/riscv/vectors_intc.S:54
[0m
[0;33m--- Warning: Failed to run gdb_panic_server.py script: Command '['riscv32-esp-elf-gdb', '--batch', '-n', '/home/happ/project/esp/esp32_as_flash_burner/build/esp32_as_flash_burner.elf', '-ex', 'target remote | "/home/happ/.espressif/python_env/idf5.4_py3.13_env/bin/python" -m esp_idf_panic_decoder --target esp32c3 "/tmp/tmpi5z6ze0j"', '-ex', 'bt']' returned non-zero exit status 1.
--- Warning: b'Traceback (most recent call last):\n  File "<frozen runpy>", line 198, in _run_module_as_main\n  File "<frozen runpy>", line 88, in _run_code\n  File "/home/happ/.espressif/python_env/idf5.4_py3.13_env/lib/python3.13/site-packages/esp_idf_panic_decoder/__main__.py", line 4, in <module>\n    main()\n    ~~~~^^\n  File "/home/happ/.espressif/python_env/idf5.4_py3.13_env/lib/python3.13/site-packages/esp_idf_panic_decoder/gdb_panic_server.py", line 289, in main\n    panic_info = PANIC_OUTPUT_PARSERS[args.target](args.input_file.read())\n  File "/home/happ/.espressif/python_env/idf5.4_py3.13_env/lib/python3.13/site-packages/esp_idf_panic_decoder/gdb_panic_server.py", line 138, in parse_idf_riscv_panic_output\n    raise ValueError("Couldn\'t parse panic handler output")\nValueError: Couldn\'t parse panic handler output\nRemote communication error.  Target disconnected: \xe8\xbf\x9e\xe6\x8e\xa5\xe8\xa2\xab\xe5\xaf\xb9\xe6\x96\xb9\xe9\x87\x8d\xe7\xbd\xae.\nNo stack.\n'

[0m
[0;33m--- 0x40380834: esp_restart_noos at /home/happ/software/esp/esp-idf/components/esp_system/port/soc/esp32c3/system_internal.c:112
[0m
[0;33m--- Stack dump detected[0m
[0;33m--- 0x42010ae8: _vfprintf_r at /builds/idf/crosstool-NG/.build/riscv32-esp-elf/src/newlib/newlib/libc/stdio/vfprintf.c:846
--- 0x42010ad6: _vfprintf_r at /builds/idf/crosstool-NG/.build/riscv32-esp-elf/src/newlib/newlib/libc/stdio/vfprintf.c:845
[0m
[0;33m--- 0x4005890e: memset in ROM
[0m
[0;33m--- 0x40380001: _vector_table at /home/happ/software/esp/esp-idf/components/riscv/vectors_intc.S:54
[0m
[0;33m--- Warning: Failed to run gdb_panic_server.py script: Command '['riscv32-esp-elf-gdb', '--batch', '-n', '/home/happ/project/esp/esp32_as_flash_burner/build/esp32_as_flash_burner.elf', '-ex', 'target remote | "/home/happ/.espressif/python_env/idf5.4_py3.13_env/bin/python" -m esp_idf_panic_decoder --target esp32c3 "/tmp/tmp4ha88xqs"', '-ex', 'bt']' returned non-zero exit status 1.
--- Warning: b'Traceback (most recent call last):\n  File "<frozen runpy>", line 198, in _run_module_as_main\n  File "<frozen runpy>", line 88, in _run_code\n  File "/home/happ/.espressif/python_env/idf5.4_py3.13_env/lib/python3.13/site-packages/esp_idf_panic_decoder/__main__.py", line 4, in <module>\n    main()\n    ~~~~^^\n  File "/home/happ/.espressif/python_env/idf5.4_py3.13_env/lib/python3.13/site-packages/esp_idf_panic_decoder/gdb_panic_server.py", line 289, in main\n    panic_info = PANIC_OUTPUT_PARSERS[args.target](args.input_file.read())\n  File "/home/happ/.espressif/python_env/idf5.4_py3.13_env/lib/python3.13/site-packages/esp_idf_panic_decoder/gdb_panic_server.py", line 138, in parse_idf_riscv_panic_output\n    raise ValueError("Couldn\'t parse panic handler output")\nValueError: Couldn\'t parse panic handler output\nRemote communication error.  Target disconnected: \xe8\xbf\x9e\xe6\x8e\xa5\xe8\xa2\xab\xe5\xaf\xb9\xe6\x96\xb9\xe9\x87\x8d\xe7\xbd\xae.\nNo stack.\n'

[0m
[0;33m--- 0x40380834: esp_restart_noos at /home/happ/software/esp/esp-idf/components/esp_system/port/soc/esp32c3/system_internal.c:112
[0m
[0;33m--- Stack dump detected[0m
[0;33m--- 0x42010ae8: _vfprintf_r at /builds/idf/crosstool-NG/.build/riscv32-esp-elf/src/newlib/newlib/libc/stdio/vfprintf.c:846
--- 0x42010ae6: _vfprintf_r at /builds/idf/crosstool-NG/.build/riscv32-esp-elf/src/newlib/newlib/libc/stdio/vfprintf.c:846
[0m
[0;33m--- 0x4005890e: memset in ROM
--- 0x403817e0: __retarget_lock_acquire_recursive at /home/happ/software/esp/esp-idf/components/newlib/locks.c:322
[0m
[0;33m--- 0x40380001: _vector_table at /home/happ/software/esp/esp-idf/components/riscv/vectors_intc.S:54
[0m
[0;33m
--- Backtrace:

[0m
[0;33m--- 0x40380834: esp_restart_noos at /home/happ/software/esp/esp-idf/components/esp_system/port/soc/esp32c3/system_internal.c:112
[0m
[0;33m--- Stack dump detected[0m
[0;33m--- 0x42010ae8: _vfprintf_r at /builds/idf/crosstool-NG/.build/riscv32-esp-elf/src/newlib/newlib/libc/stdio/vfprintf.c:846
--- 0x42010ae6: _vfprintf_r at /builds/idf/crosstool-NG/.build/riscv32-esp-elf/src/newlib/newlib/libc/stdio/vfprintf.c:846
[0m
[0;33m--- 0x4005890e: memset in ROM
--- 0x403817e0: __retarget_lock_acquire_recursive at /home/happ/software/esp/esp-idf/components/newlib/locks.c:322
[0m
[0;33m--- 0x40380001: _vector_table at /home/happ/software/esp/esp-idf/components/riscv/vectors_intc.S:54
[0m
[0;33m
--- Backtrace:

[0m
[0;33m--- 0x40380834: esp_restart_noos at /home/happ/software/esp/esp-idf/components/esp_system/port/soc/esp32c3/system_internal.c:112
[0m
[0;33m--- Stack dump detected[0m
[0;33m--- 0x42010ae8: _vfprintf_r at /builds/idf/crosstool-NG/.build/riscv32-esp-elf/src/newlib/newlib/libc/stdio/vfprintf.c:846
--- 0x42010ad6: _vfprintf_r at /builds/idf/crosstool-NG/.build/riscv32-esp-elf/src/newlib/newlib/libc/stdio/vfprintf.c:845
[0m
[0;33m--- 0x4005890e: memset in ROM
[0m
[0;33m--- 0x40380001: _vector_table at /home/happ/software/esp/esp-idf/components/riscv/vectors_intc.S:54
[0m
[0;33m
--- Backtrace:

[0m
[0;33m--- 0x40380834: esp_restart_noos at /home/happ/software/esp/esp-idf/components/esp_system/port/soc/esp32c3/system_internal.c:112
[0m
[0;33m--- Stack dump detected[0m
[0;33m--- 0x42010ae8: _vfprintf_r at /builds/idf/crosstool-NG/.build/riscv32-esp-elf/src/newlib/newlib/libc/stdio/vfprintf.c:846
--- 0x42010ad6: _vfprintf_r at /builds/idf/crosstool-NG/.build/riscv32-esp-elf/src/newlib/newlib/libc/stdio/vfprintf.c:845
[0m
[0;33m--- 0x4005890e: memset in ROM
[0m
[0;33m--- 0x40380001: _vector_table at /home/happ/software/esp/esp-idf/components/riscv/vectors_intc.S:54
[0m
[0;33m
--- Backtrace:

[0m
[0;33m--- 0x40380834: esp_restart_noos at /home/happ/software/esp/esp-idf/components/esp_system/port/soc/esp32c3/system_internal.c:112
[0m
[0;33m--- Stack dump detected[0m
[0;33m--- 0x42010ae8: _vfprintf_r at /builds/idf/crosstool-NG/.build/riscv32-esp-elf/src/newlib/newlib/libc/stdio/vfprintf.c:846
--- 0x42010ae6: _vfprintf_r at /builds/idf/crosstool-NG/.build/riscv32-esp-elf/src/newlib/newlib/libc/stdio/vfprintf.c:846
[0m
[0;33m--- 0x4005890e: memset in ROM
--- 0x403817e0: __retarget_lock_acquire_recursive at /home/happ/software/esp/esp-idf/components/newlib/locks.c:322
[0m
[0;33m--- 0x40380001: _vector_table at /home/happ/software/esp/esp-idf/components/riscv/vectors_intc.S:54
[0m
[0;33m
--- Backtrace:

[0m
[0;33m--- 0x40380834: esp_restart_noos at /home/happ/software/esp/esp-idf/components/esp_system/port/soc/esp32c3/system_internal.c:112
[0m
[0;33m--- Stack dump detected[0m
[0;33m--- 0x42010ae8: _vfprintf_r at /builds/idf/crosstool-NG/.build/riscv32-esp-elf/src/newlib/newlib/libc/stdio/vfprintf.c:846
--- 0x42010ad6: _vfprintf_r at /builds/idf/crosstool-NG/.build/riscv32-esp-elf/src/newlib/newlib/libc/stdio/vfprintf.c:845
[0m
[0;33m--- 0x4005890e: memset in ROM
[0m
[0;33m--- 0x40380001: _vector_table at /home/happ/software/esp/esp-idf/components/riscv/vectors_intc.S:54
[0m
[0;33m--- Warning: Failed to run gdb_panic_server.py script: Command '['riscv32-esp-elf-gdb', '--batch', '-n', '/home/happ/project/esp/esp32_as_flash_burner/build/esp32_as_flash_burner.elf', '-ex', 'target remote | "/home/happ/.espressif/python_env/idf5.4_py3.13_env/bin/python" -m esp_idf_panic_decoder --target esp32c3 "/tmp/tmpsxvpmd_v"', '-ex', 'bt']' returned non-zero exit status 1.
--- Warning: b'Traceback (most recent call last):\n  File "<frozen runpy>", line 198, in _run_module_as_main\n  File "<frozen runpy>", line 88, in _run_code\n  File "/home/happ/.espressif/python_env/idf5.4_py3.13_env/lib/python3.13/site-packages/esp_idf_panic_decoder/__main__.py", line 4, in <module>\n    main()\n    ~~~~^^\n  File "/home/happ/.espressif/python_env/idf5.4_py3.13_env/lib/python3.13/site-packages/esp_idf_panic_decoder/gdb_panic_server.py", line 289, in main\n    panic_info = PANIC_OUTPUT_PARSERS[args.target](args.input_file.read())\n  File "/home/happ/.espressif/python_env/idf5.4_py3.13_env/lib/python3.13/site-packages/esp_idf_panic_decoder/gdb_panic_server.py", line 152, in parse_idf_riscv_panic_output\n    stack_base_addr, stack_data = get_stack_addr_and_data(res)\n                                  ~~~~~~~~~~~~~~~~~~~~~~~^^^^^\n  File "/home/happ/.espressif/python_env/idf5.4_py3.13_env/lib/python3.13/site-packages/esp_idf_panic_decoder/gdb_panic_server.py", line 120, in get_stack_addr_and_data\n    assert base_addr == prev_base_addr + bytes_in_line\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nAssertionError\nRemote communication error.  Target disconnected: \xe8\xbf\x9e\xe6\x8e\xa5\xe8\xa2\xab\xe5\xaf\xb9\xe6\x96\xb9\xe9\x87\x8d\xe7\xbd\xae.\nNo stack.\n'

[0m
[0;33m--- 0x40380834: esp_restart_noos at /home/happ/software/esp/esp-idf/components/esp_system/port/soc/esp32c3/system_internal.c:112
[0m
[0;33m--- Stack dump detected[0m
[0;33m--- 0x42010ae8: _vfprintf_r at /builds/idf/crosstool-NG/.build/riscv32-esp-elf/src/newlib/newlib/libc/stdio/vfprintf.c:846
--- 0x42010ad6: _vfprintf_r at /builds/idf/crosstool-NG/.build/riscv32-esp-elf/src/newlib/newlib/libc/stdio/vfprintf.c:845
[0m
[0;33m--- 0x4005890e: memset in ROM
[0m
[0;33m--- 0x40380001: _vector_table at /home/happ/software/esp/esp-idf/components/riscv/vectors_intc.S:54
[0m
[0;33m
--- Backtrace:

[0m
[0;33m--- 0x40380834: esp_restart_noos at /home/happ/software/esp/esp-idf/components/esp_system/port/soc/esp32c3/system_internal.c:112
[0m
[0;33m--- Stack dump detected[0m
[0;33m--- 0x42010ae8: _vfprintf_r at /builds/idf/crosstool-NG/.build/riscv32-esp-elf/src/newlib/newlib/libc/stdio/vfprintf.c:846
--- 0x42010ae6: _vfprintf_r at /builds/idf/crosstool-NG/.build/riscv32-esp-elf/src/newlib/newlib/libc/stdio/vfprintf.c:846
[0m
[0;33m--- 0x4005890e: memset in ROM
--- 0x403817e0: __retarget_lock_acquire_recursive at /home/happ/software/esp/esp-idf/components/newlib/locks.c:322
[0m
[0;33m--- 0x40380001: _vector_table at /home/happ/software/esp/esp-idf/components/riscv/vectors_intc.S:54
[0m
[0;33m--- Warning: Failed to run gdb_panic_server.py script: Command '['riscv32-esp-elf-gdb', '--batch', '-n', '/home/happ/project/esp/esp32_as_flash_burner/build/esp32_as_flash_burner.elf', '-ex', 'target remote | "/home/happ/.espressif/python_env/idf5.4_py3.13_env/bin/python" -m esp_idf_panic_decoder --target esp32c3 "/tmp/tmp_08_m5jm"', '-ex', 'bt']' returned non-zero exit status 1.
--- Warning: b'Traceback (most recent call last):\n  File "<frozen runpy>", line 198, in _run_module_as_main\n  File "<frozen runpy>", line 88, in _run_code\n  File "/home/happ/.espressif/python_env/idf5.4_py3.13_env/lib/python3.13/site-packages/esp_idf_panic_decoder/__main__.py", line 4, in <module>\n    main()\n    ~~~~^^\n  File "/home/happ/.espressif/python_env/idf5.4_py3.13_env/lib/python3.13/site-packages/esp_idf_panic_decoder/gdb_panic_server.py", line 289, in main\n    panic_info = PANIC_OUTPUT_PARSERS[args.target](args.input_file.read())\n  File "/home/happ/.espressif/python_env/idf5.4_py3.13_env/lib/python3.13/site-packages/esp_idf_panic_decoder/gdb_panic_server.py", line 152, in parse_idf_riscv_panic_output\n    stack_base_addr, stack_data = get_stack_addr_and_data(res)\n                                  ~~~~~~~~~~~~~~~~~~~~~~~^^^^^\n  File "/home/happ/.espressif/python_env/idf5.4_py3.13_env/lib/python3.13/site-packages/esp_idf_panic_decoder/gdb_panic_server.py", line 120, in get_stack_addr_and_data\n    assert base_addr == prev_base_addr + bytes_in_line\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nAssertionError\nRemote communication error.  Target disconnected: \xe8\xbf\x9e\xe6\x8e\xa5\xe8\xa2\xab\xe5\xaf\xb9\xe6\x96\xb9\xe9\x87\x8d\xe7\xbd\xae.\nNo stack.\n'

[0m
[0;33m--- 0x40380834: esp_restart_noos at /home/happ/software/esp/esp-idf/components/esp_system/port/soc/esp32c3/system_internal.c:112
[0m
[0;33m--- Stack dump detected[0m
[1;31m--- Error: device reports readiness to read but returned no data (device disconnected or multiple access on port?)[0m
[0;33m--- Waiting for the device to reconnect[0m[0;33m--- 0x42010ae8: _vfprintf_r at /builds/idf/crosstool-NG/.build/riscv32-esp-elf/src/newlib/newlib/libc/stdio/vfprintf.c:846
--- 0x42010ae6: _vfprintf_r at /builds/idf/crosstool-NG/.build/riscv32-esp-elf/src/newlib/newlib/libc/stdio/vfprintf.c:846
[0m
[0;33m--- 0x4005890e: memset in ROM
--- 0x403817e0: __retarget_lock_acquire_recursive at /home/happ/software/esp/esp-idf/components/newlib/locks.c:322
[0m
[0;33m--- 0x40380001: _vector_table at /home/happ/software/esp/esp-idf/components/riscv/vectors_intc.S:54
[0m
[0;33m.[0m[0;33m.[0m[0;33m--- Warning: Failed to run gdb_panic_server.py script: Command '['riscv32-esp-elf-gdb', '--batch', '-n', '/home/happ/project/esp/esp32_as_flash_burner/build/esp32_as_flash_burner.elf', '-ex', 'target remote | "/home/happ/.espressif/python_env/idf5.4_py3.13_env/bin/python" -m esp_idf_panic_decoder --target esp32c3 "/tmp/tmpin5ant0p"', '-ex', 'bt']' returned non-zero exit status 1.
--- Warning: b'Traceback (most recent call last):\n  File "<frozen runpy>", line 198, in _run_module_as_main\n  File "<frozen runpy>", line 88, in _run_code\n  File "/home/happ/.espressif/python_env/idf5.4_py3.13_env/lib/python3.13/site-packages/esp_idf_panic_decoder/__main__.py", line 4, in <module>\n    main()\n    ~~~~^^\n  File "/home/happ/.espressif/python_env/idf5.4_py3.13_env/lib/python3.13/site-packages/esp_idf_panic_decoder/gdb_panic_server.py", line 289, in main\n    panic_info = PANIC_OUTPUT_PARSERS[args.target](args.input_file.read())\n  File "/home/happ/.espressif/python_env/idf5.4_py3.13_env/lib/python3.13/site-packages/esp_idf_panic_decoder/gdb_panic_server.py", line 138, in parse_idf_riscv_panic_output\n    raise ValueError("Couldn\'t parse panic handler output")\nValueError: Couldn\'t parse panic handler output\nRemote communication error.  Target disconnected: \xe8\xbf\x9e\xe6\x8e\xa5\xe8\xa2\xab\xe5\xaf\xb9\xe6\x96\xb9\xe9\x87\x8d\xe7\xbd\xae.\nNo stack.\n'

[0m
[0;33m--- 0x40380834: esp_restart_noos at /home/happ/software/esp/esp-idf/components/esp_system/port/soc/esp32c3/system_internal.c:112
[0m
[0;33m--- Stack dump detected[0m
[0;33m.[0m[0;33m--- 0x42010ae8: _vfprintf_r at /builds/idf/crosstool-NG/.build/riscv32-esp-elf/src/newlib/newlib/libc/stdio/vfprintf.c:846
--- 0x42010ad6: _vfprintf_r at /builds/idf/crosstool-NG/.build/riscv32-esp-elf/src/newlib/newlib/libc/stdio/vfprintf.c:845
[0m
[0;33m--- 0x4005890e: memset in ROM
[0m
[0;33m--- 0x40380001: _vector_table at /home/happ/software/esp/esp-idf/components/riscv/vectors_intc.S:54
[0m
[0;33m.[0m[0;33m.[0m[0;33m--- Warning: Failed to run gdb_panic_server.py script: Command '['riscv32-esp-elf-gdb', '--batch', '-n', '/home/happ/project/esp/esp32_as_flash_burner/build/esp32_as_flash_burner.elf', '-ex', 'target remote | "/home/happ/.espressif/python_env/idf5.4_py3.13_env/bin/python" -m esp_idf_panic_decoder --target esp32c3 "/tmp/tmptcv5t7q9"', '-ex', 'bt']' returned non-zero exit status 1.
--- Warning: b'Traceback (most recent call last):\n  File "<frozen runpy>", line 198, in _run_module_as_main\n  File "<frozen runpy>", line 88, in _run_code\n  File "/home/happ/.espressif/python_env/idf5.4_py3.13_env/lib/python3.13/site-packages/esp_idf_panic_decoder/__main__.py", line 4, in <module>\n    main()\n    ~~~~^^\n  File "/home/happ/.espressif/python_env/idf5.4_py3.13_env/lib/python3.13/site-packages/esp_idf_panic_decoder/gdb_panic_server.py", line 289, in main\n    panic_info = PANIC_OUTPUT_PARSERS[args.target](args.input_file.read())\n  File "/home/happ/.espressif/python_env/idf5.4_py3.13_env/lib/python3.13/site-packages/esp_idf_panic_decoder/gdb_panic_server.py", line 138, in parse_idf_riscv_panic_output\n    raise ValueError("Couldn\'t parse panic handler output")\nValueError: Couldn\'t parse panic handler output\nRemote communication error.  Target disconnected: \xe8\xbf\x9e\xe6\x8e\xa5\xe8\xa2\xab\xe5\xaf\xb9\xe6\x96\xb9\xe9\x87\x8d\xe7\xbd\xae.\nNo stack.\n'

[0m
[0;33m--- 0x40380834: esp_restart_noos at /home/happ/software/esp/esp-idf/components/esp_system/port/soc/esp32c3/system_internal.c:112
[0m
[0;33m.[0m[0;33m[0m
[0m
